### ISSUE TITLE
Please stop doing this !

### ISSUE THREAD

**Issue by incyi** [arduino-org/Arduino#10]
Why do we have now https://github.com/arduino and https://github.com/arduino-org ? Nobody likes this ! You are killing together the Arduino community ! All the new comers will stop being interested in Arduino.

**Comment by tirithen** [comment]
+1

**Comment by Isaac96** [comment]
:hamburger: 
:smiley:

**Comment by bobricius** [comment]
agree

**Comment by probonopd** [comment]
See #2

**Comment by Isaac96** [comment]
@incyi 
I agree. 
:law

**Comment by Testato** [comment]
(y)

**Comment by astrobeed** [comment]
@incyi 
I Agree.

**Comment by gpb01** [comment]
@incyi 
Totally agree !!!

**Comment by mixania** [comment]
:+1:

**Comment by Bikky-kun** [comment]
"Why do we have now https://github.com/arduino and https://github.com/arduino-org ?"
-
This might have something to do with the "Warning" that CC's Arduino IDE shouts out, when connecting a board manufactured by ORG. Such behavior is usually a precursor to more mean doing.
-
So I do understand as to why the IDE was forked.
-
Although the numbering really sucks and confuses more than it helps. Then again, any numbering would be confusing.

**Comment by Bikky-kun** [comment]
"Why do we have now https://github.com/arduino and https://github.com/arduino-org ?"
This might have something to do with the "Warning" in CC's IDE on ORG Manufactured Boards. This is just mean behavior and usually a precursor for more.
But the numbering really confuses and therefor sucks. Then again, any numbering would confuse in this case.

**Comment by Isaac96** [comment]
I think the warning was removed?
CC is at version 1.6.9 now.
