### ISSUE TITLE
serial error

### ISSUE THREAD

**Issue by xiaoyu-makeblock** [arduino-org/Arduino#13]
Error mapping
void SERCOM0_Handler()
{
	Serial.IrqHandler();
}
void SERCOM5_Handler()
{
	Serial5.IrqHandler();
}

**Comment by alfran** [comment]
Hi! 
Thank you for writing. Please give me some other information.

**Comment by quasto** [comment]
Hi @xiaoyu-makeblock, 
the issue has been solved and will be released in the next Arduino.org IDE release. 
Thanks for reporting this issue.
