### ISSUE TITLE
Arduino 1.7.8 from CLI with empty build path deletes files in home directory 

### ISSUE THREAD

**Issue by mgk** [arduino-org/Arduino#31]
### Warning: do not try and reproduce this before reading through and understanding it as reproducing the bug is destructive ###

Running the CLI to compile a sketch with an empty `build.path` preference deletes all the files in the current users home directory.

#### Versions
Platform: OS X 10.11.3
arduino.org IDE: 1.7.8

#### Repro Steps

**Important**: create new throw away user account to test with as reproducing this problem deletes files!

```
mkdir test
cd test
echo hi > ~AAA.txt
export APP=/Applications/Arduino.org.app/Contents
$APP/MacOS/Arduino --verify $APP/Java/examples/01.Basics/Blink/Blink.ino --pref build.path=
ls ~
```

Notice that  `AAA.txt` was deleted (along with any other files that existed in the users home directory).

For reference the arduino.cc IDE 1.6.7 run as above reports an error and does not delete the files in the home directory.

**Comment by sergiotomasello** [comment]
Fix will be available by the next release. Thank you @mgk for reporting the issue.
