### ISSUE TITLE
EEPROM.length removed (or missing) from IDEs 1.7.0 to 1.7.10, Fix?

### ISSUE THREAD

**Issue by DouglasBair** [arduino-org/Arduino#52]
I have developed sketches in Arduino.CC's IDEs from version 1.66 to 1.69 with the useful "EEPROM.length()".  When I 'upgraded' it doesn't exist!  
Is there no regression testing, no concern for continuity, or backward compatibility?
The comments/responses to this on the forum and blogs show no intent to reinstate it.
Please fix this if you want us to have any trust in your product.
I will stick with the original Arduino group's software until I see some progress!
Ref: www.arduino.org/forums/arduino-ide/eeprom-library-456

**Comment by sergiotomasello** [comment]
@DouglasBair #61 this PR will fix your issue

**Comment by DouglasBair** [comment]
I have tested IDE V1.7.11 relavant to the issue, it compiled, and worked in my sketch that relies on
'eeprom.length'.
Thanks, Doug

**Comment by sergiotomasello** [comment]
Thank you for report this issue.
Regards
