### ISSUE TITLE
loop between Serial.write and Serial.read on M0 pro

### ISSUE THREAD

**Issue by bilboquet** [arduino-org/Arduino#66]
Hello,

Please run the following code on a M0 pro  and do a cat /dev/ttyACM1
you should see that this code prints forever, which seems incorrect to me.
Please help me to fix it.

```
void setup() {
  Serial.begin(115200);
  Serial.println("Starting !");
}

void loop() {
    int byte, count;
    while (count = Serial.available()) {
      delay(1000);
      Serial.print("data recv on Serial : ");
      Serial.println(count);

      byte = Serial.read();
      Serial.print((char)byte);
    }
}
```

**Comment by alfran** [comment]
Hi bilboquet, I tried the code using IDE 1.7.10 and MAC OS X, and it's works fine. 
1) I used the IDE serial monitor
2) used the command  "sudo cu -l /dev/tty.usbmodem1422 -s 115200", where the tty.usbmodem1422 is the M0 pro programming port.

When I send one char, the output is "data recv on Serial : 1" for one char.
if I send the string "Ciao" I see:
"Cdata recv on Serial : 3"
"idata recv on Serial : 2"
"adata recv on Serial : 1"
"o"

This is correct.

Ciao
