### ISSUE TITLE
GSM library +CGREG: 0,0

### ISSUE THREAD

**Issue by morandbaptiste** [arduino-org/Arduino#73]
Hi, 
I have found a bug in the gsm library, We the arduino send AT+CGREG? to the gsm controler, the gsm can respond +CGREG: 0,0 this mean not registered, MT is not currently searching a new operator to register to. We have to stop sending the cmd.

**Comment by alfran** [comment]
Hi morandbaptiste,
the message you get after AT+CGREG? not depends from library, but is the reply from Quectel M10,
we can't manage this message.
